version: '3'
services:
  test_backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: 'test_backend'
    working_dir: '/home/guest/my-vue-app/backend'
    tty: true
    ports:
      - 8000:8000
    volumes:
      - $PWD/backend:/home/guest/my-vue-app/backend
    environment:
      TZ: Asia/Tokyo
    command: bash

  test_frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: 'test_frontend'
    tty: true
    volumes:
      - $PWD/frontend:/home/guest/my-vue-app/frontend
    depends_on: 
      - test_backend
    command: sh
    ports:
      - 3000:3000


  s3:
    image: minio/minio:latest
    container_name: s3
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: adminpass
    entrypoint: bash
    command: -c "mkdir -p /export/user_files && /opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio_data:/export # Persistence of MinIO storage
    ports:
      - '9000:9000'
      - '9001:9001'